// Base de datos de splits pre-configurados basados en ciencia y biomecánica

export const SPLITS_DATA = {
  'upper-lower': {
    name: 'Upper/Lower',
    description: 'División entre tren superior e inferior, ideal para frecuencia 4x semana',
    icon: 'dumbbell',
    days: {
      'Upper A': [
        { name: 'Press Banca Plano', muscleGroup: 'Pecho', sets: 3, repsRange: '6-8' },
        { name: 'Remo con Barra', muscleGroup: 'Espalda', sets: 3, repsRange: '6-8' },
        { name: 'Press Militar con Barra', muscleGroup: 'Hombros', sets: 3, repsRange: '8-10' },
        { name: 'Pulldowns Agarre Neutro', muscleGroup: 'Espalda', sets: 3, repsRange: '10-12' },
        { name: 'Press Inclinado con Mancuernas', muscleGroup: 'Pecho', sets: 3, repsRange: '10-12' },
        { name: 'Curl de Bíceps con Barra', muscleGroup: 'Bíceps', sets: 3, repsRange: '10-12' },
        { name: 'Extensiones de Tríceps en Polea', muscleGroup: 'Tríceps', sets: 3, repsRange: '12-15' },
      ],
      'Lower A': [
        { name: 'Sentadilla con Barra', muscleGroup: 'Cuádriceps', sets: 4, repsRange: '6-8' },
        { name: 'Peso Muerto Rumano', muscleGroup: 'Femorales', sets: 3, repsRange: '8-10' },
        { name: 'Prensa de Piernas', muscleGroup: 'Cuádriceps', sets: 3, repsRange: '10-12' },
        { name: 'Curl Femoral Acostado', muscleGroup: 'Femorales', sets: 3, repsRange: '10-12' },
        { name: 'Elevaciones de Pantorrilla de Pie', muscleGroup: 'Pantorrillas', sets: 4, repsRange: '12-15' },
        { name: 'Plancha Abdominal', muscleGroup: 'Core', sets: 3, repsRange: '30-60s' },
      ],
      'Upper B': [
        { name: 'Press Banca Inclinado', muscleGroup: 'Pecho', sets: 3, repsRange: '6-8' },
        { name: 'Dominadas con Lastre', muscleGroup: 'Espalda', sets: 3, repsRange: '6-8' },
        { name: 'Elevaciones Laterales', muscleGroup: 'Hombros', sets: 3, repsRange: '12-15' },
        { name: 'Remo con Mancuerna', muscleGroup: 'Espalda', sets: 3, repsRange: '10-12' },
        { name: 'Aperturas con Mancuernas', muscleGroup: 'Pecho', sets: 3, repsRange: '12-15' },
        { name: 'Curl Martillo', muscleGroup: 'Bíceps', sets: 3, repsRange: '10-12' },
        { name: 'Fondos en Paralelas', muscleGroup: 'Tríceps', sets: 3, repsRange: '8-10' },
      ],
      'Lower B': [
        { name: 'Sentadilla Frontal', muscleGroup: 'Cuádriceps', sets: 3, repsRange: '8-10' },
        { name: 'Peso Muerto Convencional', muscleGroup: 'Espalda/Femorales', sets: 3, repsRange: '5-6' },
        { name: 'Zancadas con Mancuernas', muscleGroup: 'Cuádriceps/Glúteos', sets: 3, repsRange: '10-12' },
        { name: 'Buenos Días', muscleGroup: 'Femorales/Glúteos', sets: 3, repsRange: '10-12' },
        { name: 'Elevaciones de Pantorrilla Sentado', muscleGroup: 'Pantorrillas', sets: 4, repsRange: '15-20' },
        { name: 'Rueda Abdominal', muscleGroup: 'Core', sets: 3, repsRange: '10-15' },
      ],
    },
  },
  'arnold-split': {
    name: 'Arnold Split',
    description: 'Split de 6 días popularizado por Arnold Schwarzenegger',
    icon: 'weight-lifter',
    days: {
      'Pecho/Espalda': [
        { name: 'Press Banca Plano', muscleGroup: 'Pecho', sets: 4, repsRange: '6-8' },
        { name: 'Remo con Barra', muscleGroup: 'Espalda', sets: 4, repsRange: '6-8' },
        { name: 'Press Inclinado con Mancuernas', muscleGroup: 'Pecho', sets: 3, repsRange: '8-10' },
        { name: 'Dominadas', muscleGroup: 'Espalda', sets: 3, repsRange: '8-10' },
        { name: 'Aperturas en Polea', muscleGroup: 'Pecho', sets: 3, repsRange: '12-15' },
        { name: 'Pulldowns', muscleGroup: 'Espalda', sets: 3, repsRange: '10-12' },
        { name: 'Pullover con Mancuerna', muscleGroup: 'Pecho/Espalda', sets: 3, repsRange: '12-15' },
      ],
      'Hombros/Brazos': [
        { name: 'Press Militar con Barra', muscleGroup: 'Hombros', sets: 4, repsRange: '6-8' },
        { name: 'Elevaciones Laterales', muscleGroup: 'Hombros', sets: 4, repsRange: '12-15' },
        { name: 'Pájaros', muscleGroup: 'Hombros Posterior', sets: 3, repsRange: '12-15' },
        { name: 'Curl con Barra', muscleGroup: 'Bíceps', sets: 4, repsRange: '8-10' },
        { name: 'Press Francés', muscleGroup: 'Tríceps', sets: 4, repsRange: '8-10' },
        { name: 'Curl Martillo', muscleGroup: 'Bíceps', sets: 3, repsRange: '10-12' },
        { name: 'Extensiones en Polea', muscleGroup: 'Tríceps', sets: 3, repsRange: '12-15' },
      ],
      'Piernas': [
        { name: 'Sentadilla con Barra', muscleGroup: 'Cuádriceps', sets: 5, repsRange: '6-8' },
        { name: 'Peso Muerto Rumano', muscleGroup: 'Femorales', sets: 4, repsRange: '8-10' },
        { name: 'Prensa de Piernas', muscleGroup: 'Cuádriceps', sets: 3, repsRange: '10-12' },
        { name: 'Curl Femoral', muscleGroup: 'Femorales', sets: 4, repsRange: '10-12' },
        { name: 'Extensiones de Cuádriceps', muscleGroup: 'Cuádriceps', sets: 3, repsRange: '12-15' },
        { name: 'Elevaciones de Pantorrilla', muscleGroup: 'Pantorrillas', sets: 5, repsRange: '15-20' },
      ],
    },
  },
  'ppl': {
    name: 'Push/Pull/Legs',
    description: 'División por patrones de movimiento, alta frecuencia',
    icon: 'fire',
    days: {
      'Push A': [
        { name: 'Press Banca Plano', muscleGroup: 'Pecho', sets: 4, repsRange: '6-8' },
        { name: 'Press Militar con Barra', muscleGroup: 'Hombros', sets: 3, repsRange: '6-8' },
        { name: 'Press Inclinado con Mancuernas', muscleGroup: 'Pecho', sets: 3, repsRange: '8-10' },
        { name: 'Elevaciones Laterales', muscleGroup: 'Hombros', sets: 3, repsRange: '12-15' },
        { name: 'Fondos en Paralelas', muscleGroup: 'Pecho/Tríceps', sets: 3, repsRange: '8-10' },
        { name: 'Extensiones de Tríceps en Polea', muscleGroup: 'Tríceps', sets: 3, repsRange: '12-15' },
      ],
      'Pull A': [
        { name: 'Peso Muerto Convencional', muscleGroup: 'Espalda/Femorales', sets: 3, repsRange: '5-6' },
        { name: 'Dominadas con Lastre', muscleGroup: 'Espalda', sets: 4, repsRange: '6-8' },
        { name: 'Remo con Barra', muscleGroup: 'Espalda', sets: 3, repsRange: '8-10' },
        { name: 'Face Pulls', muscleGroup: 'Hombros Posterior', sets: 3, repsRange: '15-20' },
        { name: 'Curl con Barra', muscleGroup: 'Bíceps', sets: 3, repsRange: '8-10' },
        { name: 'Curl Martillo', muscleGroup: 'Bíceps', sets: 3, repsRange: '10-12' },
      ],
      'Legs A': [
        { name: 'Sentadilla con Barra', muscleGroup: 'Cuádriceps', sets: 4, repsRange: '6-8' },
        { name: 'Peso Muerto Rumano', muscleGroup: 'Femorales', sets: 3, repsRange: '8-10' },
        { name: 'Prensa de Piernas', muscleGroup: 'Cuádriceps', sets: 3, repsRange: '10-12' },
        { name: 'Curl Femoral', muscleGroup: 'Femorales', sets: 3, repsRange: '10-12' },
        { name: 'Elevaciones de Pantorrilla', muscleGroup: 'Pantorrillas', sets: 4, repsRange: '15-20' },
      ],
      'Push B': [
        { name: 'Press Inclinado con Barra', muscleGroup: 'Pecho', sets: 4, repsRange: '6-8' },
        { name: 'Press con Mancuernas', muscleGroup: 'Hombros', sets: 3, repsRange: '8-10' },
        { name: 'Aperturas con Mancuernas', muscleGroup: 'Pecho', sets: 3, repsRange: '10-12' },
        { name: 'Elevaciones Frontales', muscleGroup: 'Hombros', sets: 3, repsRange: '12-15' },
        { name: 'Press Francés', muscleGroup: 'Tríceps', sets: 3, repsRange: '8-10' },
        { name: 'Patada de Tríceps', muscleGroup: 'Tríceps', sets: 3, repsRange: '12-15' },
      ],
      'Pull B': [
        { name: 'Remo con Mancuerna', muscleGroup: 'Espalda', sets: 4, repsRange: '8-10' },
        { name: 'Pulldowns Agarre Amplio', muscleGroup: 'Espalda', sets: 3, repsRange: '10-12' },
        { name: 'Remo en Polea Baja', muscleGroup: 'Espalda', sets: 3, repsRange: '10-12' },
        { name: 'Pájaros', muscleGroup: 'Hombros Posterior', sets: 3, repsRange: '15-20' },
        { name: 'Curl Inclinado', muscleGroup: 'Bíceps', sets: 3, repsRange: '10-12' },
        { name: 'Curl en Predicador', muscleGroup: 'Bíceps', sets: 3, repsRange: '10-12' },
      ],
      'Legs B': [
        { name: 'Sentadilla Frontal', muscleGroup: 'Cuádriceps', sets: 4, repsRange: '8-10' },
        { name: 'Buenos Días', muscleGroup: 'Femorales/Glúteos', sets: 3, repsRange: '10-12' },
        { name: 'Zancadas con Mancuernas', muscleGroup: 'Cuádriceps/Glúteos', sets: 3, repsRange: '10-12' },
        { name: 'Extensiones de Cuádriceps', muscleGroup: 'Cuádriceps', sets: 3, repsRange: '12-15' },
        { name: 'Elevaciones de Pantorrilla Sentado', muscleGroup: 'Pantorrillas', sets: 4, repsRange: '15-20' },
      ],
    },
  },
  'fullbody': {
    name: 'Full Body',
    description: 'Entrenamiento de cuerpo completo, ideal para principiantes',
    icon: 'check-decagram',
    days: {
      'Full Body A': [
        { name: 'Sentadilla con Barra', muscleGroup: 'Piernas', sets: 3, repsRange: '8-10' },
        { name: 'Press Banca Plano', muscleGroup: 'Pecho', sets: 3, repsRange: '8-10' },
        { name: 'Remo con Barra', muscleGroup: 'Espalda', sets: 3, repsRange: '8-10' },
        { name: 'Press Militar', muscleGroup: 'Hombros', sets: 3, repsRange: '10-12' },
        { name: 'Peso Muerto Rumano', muscleGroup: 'Femorales', sets: 3, repsRange: '10-12' },
        { name: 'Plancha Abdominal', muscleGroup: 'Core', sets: 3, repsRange: '30-60s' },
      ],
      'Full Body B': [
        { name: 'Peso Muerto Convencional', muscleGroup: 'Espalda/Piernas', sets: 3, repsRange: '6-8' },
        { name: 'Press Inclinado con Mancuernas', muscleGroup: 'Pecho', sets: 3, repsRange: '8-10' },
        { name: 'Dominadas', muscleGroup: 'Espalda', sets: 3, repsRange: '8-10' },
        { name: 'Zancadas con Mancuernas', muscleGroup: 'Piernas', sets: 3, repsRange: '10-12' },
        { name: 'Elevaciones Laterales', muscleGroup: 'Hombros', sets: 3, repsRange: '12-15' },
        { name: 'Curl de Bíceps', muscleGroup: 'Bíceps', sets: 2, repsRange: '10-12' },
        { name: 'Extensiones de Tríceps', muscleGroup: 'Tríceps', sets: 2, repsRange: '10-12' },
      ],
      'Full Body C': [
        { name: 'Sentadilla Frontal', muscleGroup: 'Piernas', sets: 3, repsRange: '8-10' },
        { name: 'Aperturas con Mancuernas', muscleGroup: 'Pecho', sets: 3, repsRange: '10-12' },
        { name: 'Remo con Mancuerna', muscleGroup: 'Espalda', sets: 3, repsRange: '10-12' },
        { name: 'Press con Mancuernas', muscleGroup: 'Hombros', sets: 3, repsRange: '10-12' },
        { name: 'Curl Femoral', muscleGroup: 'Femorales', sets: 3, repsRange: '10-12' },
        { name: 'Rueda Abdominal', muscleGroup: 'Core', sets: 3, repsRange: '10-15' },
      ],
    },
  },
};
